# Generated by Django 3.1.6 on 2021-02-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcomponent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
