# Generated by Django 3.1.6 on 2021-02-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcomponent', '0005_auto_20210222_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='testcomponent.Tag'),
        ),
    ]
