# Generated by Django 3.1.6 on 2021-02-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcomponent', '0006_auto_20210222_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Summer', 'Summer'), ('Kitchen', 'Kitchen')], max_length=200, null=True),
        ),
    ]
